CREATE OR REPLACE TYPE Direccion AS OBJECT
(
    Pais      VARCHAR2(20),
    Ciudad    VARCHAR2(20),
    Direccion VARCHAR2(40)
);

CREATE OR REPLACE TYPE NombreCompleto AS OBJECT
(
    Nombre    VARCHAR2(30),
    Apellido1 VARCHAR2(30),
    Apellido2 VARCHAR2(30)
);

CREATE OR REPLACE TYPE NumTel AS OBJECT
(
    Especificacion VARCHAR2(20),
    NumTelefono    NUMBER
);

-- Coleccion de numeros de Telefono
CREATE TYPE NumTelefonos as
    VARRAY (4) of NumTel;


CREATE OR REPLACE TYPE Correo AS OBJECT
(
    Especificacion VARCHAR2(20),
    Correo         VARCHAR2(40)
);

-- Coleccion de Correos
CREATE TYPE Correos as
    VARRAY (4) of Correo;


CREATE OR REPLACE TYPE Paquete AS OBJECT
(
    Descripcion   VARCHAR2(40),
    Peso          NUMBER
);

-- Coleccion de Paquetes
CREATE TYPE Paquetes as
    VARRAY (10) of Paquete;




-- DROP TABLE ESTADOENVIO;
-- DROP TABLE PROCESOENVIO;
-- DROP TABLE PESORANGO;
-- DROP TABLE DISTANCIARANGO;
-- DROP TABLE CONDICIONPAQUETE;
-- DROP TABLE DISTANCIAXSUCURSAL;
-- DROP TABLE DISTRIBUCION;
-- DROP TABLE ENVIO;
-- DROP TABLE SUCURSAL;
-- DROP TABLE CLIENTE;
-- DROP TABLE EMPLEADO;
-- DROP TABLE TIPOSERVICIO;
-- DROP TABLE TIPOEMPLEO;
-- DROP TABLE PERSONA;
-- DROP TYPE NOMBRECOMPLETO;
-- DROP TYPE Correos;
-- DROP TYPE Correo;
-- DROP TYPE NumTelefonos;
-- DROP TYPE NumTel;
-- DROP TYPE DIRECCION;
-- DROP TYPE Paquetes;
-- DROP TYPE Paquete;

--
-- SELECT * FROM  ESTADOENVIO;
-- SELECT * FROM  PROCESOENVIO;
-- SELECT * FROM  PESORANGO;
-- SELECT * FROM DISTANCIARANGO;
-- SELECT * FROM  CONDICIONPAQUETE;
-- SELECT * FROM  DISTANCIAXSUCURSAL;
-- SELECT * FROM  DISTRIBUCION;
-- SELECT * FROM  ENVIO;
-- SELECT * FROM  SUCURSAL;
-- SELECT * FROM CLIENTE;
-- SELECT * FROM  EMPLEADO;
-- SELECT * FROM TIPOSERVICIO;
-- SELECT * FROM  TIPOEMPLEO;
-- SELECT * FROM PERSONA;
